### ISSUE TITLE
Video missing

### ISSUE THREAD

**Issue by AlexNodex** [rajikaimal/awesome-express#1]
Express crash course video does not exist due to the account that created it being terminated.

**Comment by rajikaimal** [comment]
@AlexNodex Thank you for reporting this, feel free to add a PR for this by removing the resource/link.

**Comment by AlexNodex** [comment]
Hi

I'm not sure how to do pull requests sorry

**Comment by rajikaimal** [comment]
You can fork this repository and work on the changes with your fork. After that you can submit a PR, that's if you're interested in that, or I'll do the change shortly.

**Comment by rajikaimal** [comment]
Solves with [d5443fb](https://github.com/rajikaimal/awesome-express/commit/f9fecef2c874218325be12affd2ed5eb791e72ad)
